

services:
  php:
    image: php:8.2-apache
    volumes:
      - ./src:/var/www/html/
      - ./config/apache-custom.conf:/usr/local/apache2/conf/extra/apache-custom.conf
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: mydatabase
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db


